# 1. Eliminación de Gauss

In [94]:
A=[-0.04 0.04 0.12 ; 0.56 -1.56 0.32 ; -0.24 1.24 -0.28];
y=[3; 1 ;0];

In [95]:
rank(A)

3

In [77]:
norm(A)*norm(inv(A))

23.04937309342708

In [80]:
inv(A)

3×3 Matrix{Float64}:
 1.0  4.0  5.0
 2.0  1.0  2.0
 8.0  1.0  1.0

In [4]:
A

3×3 Matrix{Float64}:
 -0.04   0.04   0.12
  0.56  -1.56   0.32
 -0.24   1.24  -0.28

creamos la matriz ampliada $[A y]$

In [5]:
A_c=[A y]

3×4 Matrix{Float64}:
 -0.04   0.04   0.12  3.0
  0.56  -1.56   0.32  1.0
 -0.24   1.24  -0.28  0.0

1.1) Tomamos la primera fila de la matriz aumentada como pivote y creamos el multiplicador $m_{2,1}$. Luego restamos la segunda fila con el pivote y el multipicador. 

In [6]:
P=A_c[1,:];
m21=A_c[2,1]/A_c[1,1];
A_c[2,:]-=m21*P;

In [7]:
A_c

3×4 Matrix{Float64}:
 -0.04   0.04   0.12   3.0
  0.0   -1.0    2.0   43.0
 -0.24   1.24  -0.28   0.0

2.2) Creamos el multiplicador $m_{3,1}$. Luego restamos la tercera fila con el pivote y el multipicador. 

In [8]:
m31=A_c[3,1]/A_c[1,1];
A_c[3,:]-=m31*P;

In [9]:
A_c

3×4 Matrix{Float64}:
 -0.04   0.04   0.12    3.0
  0.0   -1.0    2.0    43.0
  0.0    1.0   -1.0   -18.0

1.3) Tomamos la segunda fila de la matriz aumentada como pivote y creamos el multiplicador $m_{3,2}$. Luego restamos la tercera fila con el pivote y el multipicador. 

In [10]:
P=A_c[2,:]
m32=A_c[3,2]/A_c[2,2];
A_c[3,:]-=m32*P;

In [11]:
A_c

3×4 Matrix{Float64}:
 -0.04   0.04  0.12   3.0
  0.0   -1.0   2.0   43.0
  0.0    0.0   1.0   25.0

1.4) Resolvemos la tercera ecuación para $x_3=25$. Luego sustuimos en $-x_2+2*25=43$ y obtenemos $x_2=7$.

Finalmente sustituimos $x_1$ y $x_2$ en la primera ecuación $-004*x_1+0.004*x_2+0.12*x_3=3$ y obtenemos $x_1=7$.

In [12]:
# Algoritmo 1.1 VMLS https://web.stanford.edu/~boyd/vmls/

function back_subst(R,b)
    n = length(b)
    x = zeros(n)
    for i=n:-1:1
        x[i] = (b[i] - R[i,i+1:n]'*x[i+1:n]) / R[i,i]
    end
    return x
end;

In [15]:
x_gauss=back_subst(A_c[:,1:3],A_c[:,4])

3-element Vector{Float64}:
  7.000000000000028
  7.000000000000007
 25.000000000000007

En Julia podemos resolver directamente el sistema de ecuaciones mediante el operador \ 

In [17]:
x_ls=A\y;

In [19]:
using LinearAlgebra;

norm(x_gauss-x_ls)

2.4741787777998282e-14

# 2) Ejercicios 

2.1) Resolver el siguiente sistema de ecuaciones lineales usando el método de eliminación de Gauss: $\boldsymbol{A}\boldsymbol{x}=\boldsymbol{y}$ para la matriz de Hilbert de tamaño $3 \times 3$:

$\boldsymbol{A}=\begin{bmatrix} 1/2 & 1/3 & 1/4 \\
                                1/3 & 1/4 & 1/5 \\
                                1/4 & 1/5 & 1/6 \\
                \end{bmatrix}$, 
$\boldsymbol{y}=\begin{bmatrix} 1 \\
                                1 \\
                                1 \\
                \end{bmatrix}$

2.2) Comprobar los resultados con los valores obtenidos.

2.3) Una forma de evaluar la existencia de la solución de un sistema de ecuaciones es a través del número de condicionamiento:

$cond(A)=||A||\times ||A^{-1}|| $, donde $||\cdot||$ es la norma de la matriz. Revise el determinante y el número de condicionamiento de la matriz de ejercicio 1.5.

2.4) Construya una matriz de Hilbert de tamaño $20 \times 20$ y repita el procedimiento anterior. ¿La matriz resultante es invertible? ¿Cuanto cambia el número de condicionamiento.? 

$A=[\frac{1}{i+j-1}],i,j=1:20$

In [57]:
function hilbert(n::Int64)::Matrix
    A=ones(n,n)
    for i=1:n
        for j=1:n
            A[i,j]=1/(i+j-1)
        end
    end
    return A 
end

hilbert (generic function with 1 method)

2.5) Resolver el siguiente sistema de ecuaciones lineales mediante eliminación de Gauss:

$\boldsymbol{A}=\begin{bmatrix} 2 & 4 & 6 \\
                                2 & 0 & 2 \\
                                6 & 8 &14 \\
                \end{bmatrix}$, 
$\boldsymbol{y}=\begin{bmatrix} 1 \\
                                1 \\
                                1 \\
                \end{bmatrix}$

In [44]:
# 2.1

A=[ 1/2  1/3  1/4; 1/3  1/4 1/5; 1/4  1/5  1/6];
y=ones(3);

A_c=[A y];
P=A_c[1,:];
m21=A_c[2,1]/A_c[1,1];
A_c[2,:]-=m21*P;
m31=A_c[3,1]/A_c[1,1];
A_c[3,:]-=m31*P;
P=A_c[2,:]
m32=A_c[3,2]/A_c[2,2];
A_c[3,:]-=m32*P;
x_gauss=back_subst(A_c[:,1:3],A_c[:,4])

3-element Vector{Float64}:
  12.000000000000394
 -60.000000000001585
  60.000000000001315

In [45]:
x_ls=A\y

3-element Vector{Float64}:
  12.000000000000416
 -60.00000000000164
  60.00000000000136

In [52]:
1/det(A)

43200.00000000099

In [48]:
cond=norm(A)*norm(inv(A))

1354.9345814466783

In [25]:
norm(x_gauss-x_ls)

7.418283949015283e-14

In [55]:
# introducimos una perturbacion en la diagonal de A

A=[ 1/2  1/3  1/4; 1/3  1/4 1/5; 1/4  1/5  1/6]+Diagonal(ones(3))*1e-8;
y=ones(3);

A_c=[A y];
P=A_c[1,:];
m21=A_c[2,1]/A_c[1,1];
A_c[2,:]-=m21*P;
m31=A_c[3,1]/A_c[1,1];
A_c[3,:]-=m31*P;
P=A_c[2,:]
m32=A_c[3,2]/A_c[2,2];
A_c[3,:]-=m32*P;
x_gauss=back_subst(A_c[:,1:3],A_c[:,4])

3-element Vector{Float64}:
  11.999739364054529
 -59.99899921549251
  59.999186412558046

In [56]:
norm(x_gauss-x_ls)

0.0013158363340164338

In [60]:
# 2.4 Matriz de Hilbert

A=hilbert(20);
y=ones(20);

In [61]:
cond=norm(A)*norm(inv(A))

2.583006774892072e18

In [63]:
det(A)

-9.026862380917484e-195

In [66]:
x_ls=A\y;

In [67]:
A_p=A+Diagonal(ones(20))*1e-8;
x_ls_p=A_p\y;

In [68]:
norm(x_ls-x_ls_p)

2.6661447241844845e9

In [86]:
# 2.5 

A= [2 4 6;2 0 2;6 8 14];
y=ones(3);

In [87]:
cond=norm(A)*norm(inv(A))

4.531659709609418e16

In [93]:
rank(A)

2

In [89]:
x_ls=A\y

3-element Vector{Float64}:
 -1.125899906842624e15
 -1.125899906842624e15
  1.125899906842624e15

In [90]:
A_c=[A y];
P=A_c[1,:];
m21=A_c[2,1]/A_c[1,1];
A_c[2,:]-=m21*P;
m31=A_c[3,1]/A_c[1,1];
A_c[3,:]-=m31*P;
P=A_c[2,:]
m32=A_c[3,2]/A_c[2,2];
A_c[3,:]-=m32*P;


In [91]:
A_c

3×4 Matrix{Float64}:
 2.0   4.0   6.0   1.0
 0.0  -4.0  -4.0   0.0
 0.0   0.0   0.0  -2.0

In [92]:
x_gauss=back_subst(A_c[:,1:3],A_c[:,4])

3-element Vector{Float64}:
 NaN
  Inf
 -Inf