# Minimos Cuadrados

Supongamos que se necesita resolver un sistema de ecuaciones $\boldsymbol{A}\boldsymbol{x}=\boldsymbol{y}$ sobre-determinado.

En este caso, contamos con mayor numero de ecuaciones que inconitas. Por lo tanto, la matriz $\boldsymbol{A}$ no es cuadrada y por consiguiente, tiene $m$ filas y $n$ columnas para $m>n$.

En vez de resolver el sistema de ecuaciones $\boldsymbol{A}\boldsymbol{x}=\boldsymbol{y}$, trataremos de encontrar una aproximación por mínimos cuadrados:

$\operatorname{min} \frac{1}{2}|\boldsymbol{A}\boldsymbol{x}-\boldsymbol{y}|^2$.

Ahora, tenemos que comprobar que $\boldsymbol{A}$ es de rango $n$ y por lo tanto, existen tantas ecuaciones linealmente independientes como incógnitas y por lo tanto existe una solución 


## Solución de Mínimos Cuadrados

Si el rango de $\boldsymbol{A}$ es $n$, entonces la matriz $\boldsymbol{A}^T \boldsymbol{A}$ es una matriz $n\times n$ cuya inversa existe.

Por lo tanto, la solución del problema está dada por:

$\boldsymbol{x}=(\boldsymbol{A}^T \boldsymbol{A})^{-1}\boldsymbol{A}^T\boldsymbol{y}$

En este caso, la matriz $\boldsymbol{A}^{\dagger}=(\boldsymbol{A}^T \boldsymbol{A})^{-1}\boldsymbol{A}^T$ es la pseudo-inversa de $\boldsymbol{A}$, ya que $\boldsymbol{A}^{\dagger}\boldsymbol{A}=I$

In [1]:
using LinearAlgebra;

A=rand(Float64, (10, 3))

10×3 Matrix{Float64}:
 0.071208  0.863571  0.221761
 0.523812  0.572305  0.498935
 0.178145  0.204695  0.026689
 0.441131  0.614137  0.793414
 0.992092  0.150187  0.0790369
 0.530195  0.139028  0.536149
 0.240656  0.619062  0.634121
 0.590255  0.403523  0.728893
 0.559656  0.192165  0.534428
 0.150307  0.742962  0.188794

In [2]:
print("El rango de la matriz A es ",rank(A))

El rango de la matriz A es 3

In [5]:
inv(transpose(A)*A)*transpose(A)

3×10 Matrix{Float64}:
 -0.0768591   0.138258    0.155303  …   0.0235557   0.135691   0.0203998
  0.634644    0.163746    0.174468     -0.167338   -0.215727   0.549873
 -0.360212   -0.0361784  -0.248562      0.410358    0.284393  -0.380356

In [6]:
pinv(A)

3×10 Matrix{Float64}:
 -0.0768591   0.138258    0.155303  …   0.0235557   0.135691   0.0203998
  0.634644    0.163746    0.174468     -0.167338   -0.215727   0.549873
 -0.360212   -0.0361784  -0.248562      0.410358    0.284393  -0.380356

calculamos la pseudo-inversa mediante la función pinv, lo cual nos permite comprobar que aunque $A$ no es una matriz cuadrada, la seudoinversa actua de la misma forma que la inversa.  

In [7]:
pinv(A)*A ≈ Diagonal(ones(3))

true

In [9]:
pinv(A)*A

3×3 Matrix{Float64}:
  1.0          -2.98372e-16  -2.22478e-16
 -4.71845e-16   1.0           0.0
  4.44089e-16   2.22045e-16   1.0

Ahora podemos calcular el numero de condicionamiento $cond(A)=||A||\times ||A^{\dagger}|| $, donde $||\cdot||$ es la norma de la matriz no cuadrada.

In [10]:
norm(A)*norm(pinv(A))

5.16454350084032

# 2) Ejercicios 

2.1) Resolver el siguiente sistema de ecuaciones lineales usando el método de minimos cuadrados: $\boldsymbol{A}\boldsymbol{x}=\boldsymbol{y}$. Verifique el rango, condicionamiento y existencia de la pseudo-inversa.

$\boldsymbol{A}=\begin{bmatrix} 2 & 4 & 2\\
                                1 & 1 & 3\\
                                4 & 2 & 2\\
                                2 & 5 & 3\\
                                2 & 1 & 1\\
                \end{bmatrix}$, 
$\boldsymbol{y}=\begin{bmatrix} 82\\
                                38\\
                                118\\
                                91\\
                                59\\
                \end{bmatrix}$

2.2)Use un sistema de ecuaciones para predecir el consumo de gasolina de un vehiculo dependiendo del peso, desplazamiento, caballos de fuerza y aceleración de este. Descargue los datos desde :

https://archive.ics.uci.edu/ml/datasets/auto+mpg

In [32]:
file=Downloads.download("https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data")

"/var/folders/wd/0sm_658d23ldnfyfjn6y4s6m0000gn/T/jl_lz7J9J"